CATEGORY_MAPPING = {

    # BILLS_SUBSCRIPTIONS
    0: 0,   # BILLS_SUBSCRIPTIONS_BILLS => BILLS_SUBSCRIPTIONS
    1: 0,   # BILLS_SUBSCRIPTIONS_INTERNET_PHONE => BILLS_SUBSCRIPTIONS
    2: 0,   # BILLS_SUBSCRIPTIONS_OTHER => BILLS_SUBSCRIPTIONS
    3: 0,   # BILLS_SUBSCRIPTIONS_SUBSCRIPTIONS => BILLS_SUBSCRIPTIONS

    # GROCERIES
    18: 1,  # HOUSING_FAMILY_GROCERIES => GROCERIES

    # EATING_OUT
    5: 2,   # EATING_OUT_COFFEE_SHOPS => EATING_OUT
    6: 2,   # EATING_OUT_OTHER => EATING_OUT
    7: 2,   # EATING_OUT_RESTAURANTS => EATING_OUT
    8: 2,   # EATING_OUT_TAKEAWAY_RESTAURANTS => EATING_OUT

    # TRANSPORTATION
    61: 3,  # TRAVELS_TRANSPORTATION_BUSES => TRANSPORTATION
    62: 3,  # TRAVELS_TRANSPORTATION_CAR_RENTAL => TRANSPORTATION
    64: 3,  # TRAVELS_TRANSPORTATION_FUEL => TRANSPORTATION
    67: 3,  # TRAVELS_TRANSPORTATION_PARKING_URBAN_TRANSPORTS => TRANSPORTATION
    68: 3,  # TRAVELS_TRANSPORTATION_TAXIS => TRANSPORTATION
    69: 3,  # TRAVELS_TRANSPORTATION_TOLLS => TRANSPORTATION
    70: 3,  # TRAVELS_TRANSPORTATION_TRAINS => TRANSPORTATION
    72: 3,  # TRAVELS_TRANSPORTATION_VEHICLE_MAINTENANCE => TRANSPORTATION

    # CLOTHING
    41: 4,  # SHOPPING_ACCESSORIZE => CLOTHING
    42: 4,  # SHOPPING_CLOTHING => CLOTHING
    43: 4,  # SHOPPING_FOOTWEAR => CLOTHING

    # HEALTH_WELLNESS
    9: 5,   # HEALTH_WELLNESS_AID_EXPENSES => HEALTH_WELLNESS
    10: 5,  # HEALTH_WELLNESS_DRUGS => HEALTH_WELLNESS
    11: 5,  # HEALTH_WELLNESS_GYMS => HEALTH_WELLNESS
    12: 5,  # HEALTH_WELLNESS_MEDICAL_EXPENSES => HEALTH_WELLNESS
    13: 5,  # HEALTH_WELLNESS_OTHER => HEALTH_WELLNESS
    14: 5,  # HEALTH_WELLNESS_WELLNESS_RELAX => HEALTH_WELLNESS

    # SHOPPING
    44: 6,  # SHOPPING_HI_TECH => SHOPPING
    45: 6,  # SHOPPING_OTHER => SHOPPING
    46: 6,  # SHOPPING_SPORT_ARTICLES => SHOPPING

    # LEISURE_ENTERTAINMENT
    25: 7,  # LEISURE_BOOKS => LEISURE_ENTERTAINMENT
    26: 7,  # LEISURE_CINEMA => LEISURE_ENTERTAINMENT
    27: 7,  # LEISURE_CLUB_ASSOCIATIONS => LEISURE_ENTERTAINMENT
    28: 7,  # LEISURE_GAMBLING => LEISURE_ENTERTAINMENT
    29: 7,  # LEISURE_MAGAZINES_NEWSPAPERS => LEISURE_ENTERTAINMENT
    30: 7,  # LEISURE_MOVIES_MUSICS => LEISURE_ENTERTAINMENT
    31: 7,  # LEISURE_OTHER => LEISURE_ENTERTAINMENT
    32: 7,  # LEISURE_SPORT_EVENTS => LEISURE_ENTERTAINMENT
    33: 7,  # LEISURE_THEATERS_CONCERTS => LEISURE_ENTERTAINMENT
    34: 7,  # LEISURE_VIDEOGAMES => LEISURE_ENTERTAINMENT

    # HOME_MAINTENANCE
    15: 8,  # HOUSING_FAMILY_APPLIANCES => HOME_MAINTENANCE
    17: 8,  # HOUSING_FAMILY_FURNITURE => HOME_MAINTENANCE
    20: 8,  # HOUSING_FAMILY_MAINTENANCE_RENOVATION => HOME_MAINTENANCE

    # PERSONAL_CARE
    9: 9,   # HEALTH_WELLNESS_AID_EXPENSES => PERSONAL_CARE
    24: 9,  # HOUSING_FAMILY_VETERINARY => PERSONAL_CARE

    # TAVEL_DAILY
    63: 10, # TRAVELS_TRANSPORTATION_FLIGHTS => TRAVEL_DAILY
    65: 10, # TRAVELS_TRANSPORTATION_HOTELS => TRAVEL_DAILY
    66: 10, # TRAVELS_TRANSPORTATION_OTHER => TRAVEL_DAILY
    71: 10, # TRAVELS_TRANSPORTATION_TRAVELS_HOLIDAYS => TRAVEL_DAILY

    # WGES_INCOME
    73: 11, # WAGES_PENSION => WAGES_INCOME
    74: 11, # WAGES_PROFESSIONAL_COMPENSATION => WAGES_INCOME
    75: 11, # WAGES_SALARY => WAGES_INCOME

    # TANSFERS
    54: 12, # TRANSFERS_BANK_TRANSFERS => TRANSFERS
    55: 12, # TRANSFERS_GIFTS_DONATIONS => TRANSFERS
    56: 12, # TRANSFERS_INVESTMENTS => TRANSFERS
    57: 12, # TRANSFERS_OTHER => TRANSFERS
    58: 12, # TRANSFERS_REFUNDS => TRANSFERS
    59: 12, # TRANSFERS_RENT_INCOMES => TRANSFERS
    60: 12, # TRANSFERS_SAVINGS => TRANSFERS

    # OHER
    37: 99, # OTHER_CASH => OTHER
    38: 99, # OTHER_CHECKS => OTHER
    39: 99, # OTHER_OTHER => OTHER
    40: 99, # PROFITS_PROFITS => OTHER
    47: 99, # TAXES_SERVICES_BANK_FEES => OTHER
    48: 99, # TAXES_SERVICES_DEFAULT_PAYMENTS => OTHER
    49: 99, # TAXES_SERVICES_MONEY_ORDERS => OTHER
    50: 99, # TAXES_SERVICES_OTHER => OTHER
    51: 99, # TAXES_SERVICES_PROFESSIONAL_ACTIVITY => OTHER
    52: 99, # TAXES_SERVICES_PROFIT_DEDUCTION => OTHER
    53: 99, # TAXES_SERVICES_TAXES => OTHER
}